name: Playwright DMS Test (Auto Run)

on:
  schedule:
    - cron: "0 */3 * * *" # setiap 3 jam sekali
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add custom hosts
        run: |
          echo "123.45.67.89   api.example.com" | sudo tee -a /etc/hosts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Fix Playwright permission (important)
        run: chmod +x node_modules/.bin/playwright

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          DMS_USERNAME: ${{ secrets.DMS_USERNAME }}
          DMS_PASSWORD: ${{ secrets.DMS_PASSWORD }}
        run: npx playwright test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: reports/
